### ISSUE TITLE
Mod shows death +use message whenever +use is pressed, even while alive

### ISSUE THREAD

**Issue by Gemini04126** [CandiceJoy/ExtraLivesMod#1] opened 2023-01-24 01:32 UTC
![image](https://user-images.githubusercontent.com/8532523/214194678-b1682c53-022c-4842-bb67-03be8a75a89c.png)

This happens at any time, dead or alive. I looked at the ZScript and there doesn't seem to be a check for whether or not the player is actually dead, so it just disables the +use key.

**Comment by CandiceJoy** [comment] 2023-01-24 01:38
Fixed in https://github.com/CandiceJoy/ExtraLivesMod/commit/52c6c5215efe9f72c9f880d824af679562924018 :D  New build uploaded [here](https://forum.zdoom.org/viewtopic.php?p=1235101) ^_^

**Closed as completed by CandiceJoy** 2023-01-24 01:38 UTC

**Comment by Gemini04126** [comment] 2023-01-24 01:59
Unfortunately, fixing this caused something else (just really minor) to crop up: Once all lives have run out, you can't press +use to continue, since you're dead. Maybe a lives check alongside the dead check would work?

**Comment by CandiceJoy** [comment] 2023-01-24 02:03
That's correct, that's the intended behaviour.  Once you run out of lives and die, you are not allowed to do anything but start a new game :)
